# Generated by Django 3.1.5 on 2021-02-27 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changesinuserinformation',
            name='new_first_name',
            field=models.CharField(max_length=150, null=True, verbose_name="Нове ім'я"),
        ),
        migrations.AlterField(
            model_name='changesinuserinformation',
            name='new_last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Нова фамілія'),
        ),
        migrations.AlterField(
            model_name='changesinuserinformation',
            name='new_phone_number',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^(\\s*)?(\\+)?([- _():=+]?\\d[- _():=+]?){10,14}(\\s*)?$')], verbose_name='Номер телефона'),
        ),
    ]
