# Generated by Django 3.1.5 on 2021-02-18 18:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceduser',
            name='Дата народження',
        ),
        migrations.RemoveField(
            model_name='advanceduser',
            name='Номер телефона',
        ),
        migrations.AddField(
            model_name='advanceduser',
            name='date_of_birth',
            field=models.CharField(max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Example: 21.01.2001', regex='^(?:0[1-9]|[12]\\d|3[01])([\\/.-])(?:0[1-9]|1[012])\\1(?:19|20)\\d\\d$')], verbose_name='Дата народження'),
        ),
        migrations.AddField(
            model_name='advanceduser',
            name='phone_number',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^(\\s*)?(\\+)?([- _():=+]?\\d[- _():=+]?){10,14}(\\s*)?$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='village',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.villagesofbershad', verbose_name='Місто/село'),
        ),
    ]
