# Generated by Django 3.1.5 on 2021-02-18 18:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210218_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='villagesofbershad',
            options={'verbose_name': 'Населений пункт', 'verbose_name_plural': 'Населені пункти'},
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Example: 21.01.2001', regex='^(?:0[1-9]|[12]\\d|3[01])([\\/.-])(?:0[1-9]|1[012])\\1(?:19|20)\\d\\d$')], verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^(\\s*)?(\\+)?([- _():=+]?\\d[- _():=+]?){10,14}(\\s*)?$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='village',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.villagesofbershad', verbose_name='Місто/село'),
        ),
        migrations.AlterField(
            model_name='villagesofbershad',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Назва'),
        ),
    ]
