# Generated by Django 3.1.5 on 2021-02-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210218_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='village',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.villagesofbershad', verbose_name='Місто/село'),
        ),
    ]
