# Generated by Django 3.1.5 on 2021-02-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210218_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='village',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.villagesofbershad', verbose_name='Місто/село'),
        ),
    ]
