# Generated by Django 3.1.5 on 2021-03-09 22:44

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210310_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
