# Generated by Django 3.1.5 on 2021-02-18 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210218_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Example: 21.01.2001', regex='^(?:0[1-9]|[12]\\d|3[01])([\\/.-])(?:0[1-9]|1[012])\\1(?:19|20)\\d\\d$')], verbose_name='Дата народження'),
        ),
    ]
