# Generated by Django 3.1.5 on 2021-02-19 20:18

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210218_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advanceduser',
            old_name='username_slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[main.validators.date_of_birth_validator], verbose_name='Дата народження'),
        ),
    ]
