# Generated by Django 3.1.5 on 2021-02-19 20:49

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210219_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Користувач з таким іменем уже був зареєстрований раніше.'}, help_text='Вимоги: від шести до двадцяти чотирьох символів (6-24). Букви латинського алфавіту, цифри та символи -,_', max_length=24, unique=True, validators=[main.validators.username_validator]),
        ),
    ]
