# Generated by Django 3.1.5 on 2021-02-21 18:41

import django.core.validators
from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210219_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email адреса'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\s*)?(\\+)?([- _():=+]?\\d[- _():=+]?){10,14}(\\s*)?$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Користувач з таким іменем уже був зареєстрований раніше.'}, help_text='Вимоги: від шести до двадцяти чотирьох символів (6-24). Букви латинського алфавіту, цифри та символ _', max_length=24, unique=True, validators=[main.validators.username_validator], verbose_name='Нікнейм'),
        ),
        migrations.AlterField(
            model_name='villagesofbershad',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
