# Generated by Django 3.1.5 on 2021-02-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210221_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceduser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Підтвердіть свій аккаунт, перейшовши за посиланням, яку було надіслано на Вашу email адресу.'),
        ),
    ]
