# Generated by Django 3.1.5 on 2021-02-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_advanceduser_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceduser',
            name='is_activated',
            field=models.BooleanField(default=False, help_text='Параметр стає активним, коли користувач підтвердить свою електронну адресу.'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
